#!/usr/bin/env node

var Sandbox = require('./sandbox');
var PassthroughApi = require('./lib/api/passthrough').PassthroughApi;

var sandbox = new Sandbox({
  api: PassthroughApi,
  disableNaCl: process.env.NONACL || false,
  enableGdb: process.env.ENABLE_GDB || false,
  enableValgrind: process.env.ENABLE_VALGRIND || false
});
// console.log('Running file in Codius sandbox: ' + process.argv[2]);
sandbox.run('', process.argv[2]);