#!/bin/bash

export TOOLCHAIN=$NACL_SDK_ROOT/toolchain/linux_x86_glibc/
export PATH=$TOOLCHAIN/bin:$PATH
export AR=x86_64-nacl-ar
export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LINK=x86_64-nacl-g++

./configure \
    --debug \
    --without-snapshot \
    --dest-cpu=ia32 \
    --dest-os=linux \
    --shared-v8 \
    --shared-v8-includes=deps/v8/include \
    --shared-v8-libpath=../deps/v8/out/nacl_ia32.release/lib.target \
    --without-ssl
    