#!/bin/bash

export TOOLCHAIN=$NACL_SDK_ROOT/toolchain/linux_x86_glibc/
export PATH=$TOOLCHAIN/bin:$PATH
export AR=x86_64-nacl-ar
export CC=x86_64-nacl-gcc
export CXX=x86_64-nacl-g++
export LINK=x86_64-nacl-g++

./configure \
    --debug \
    --without-snapshot \
    --dest-cpu=ia32 \
    --dest-os=linux \
    --shared-openssl \
    --shared-openssl-includes=/deps/openssl/openssl/include/openssl \
    --shared-openssl-libpath=$TOOLCHAIN/x86_64-nacl/usr/lib
    # --shared-v8 \
    # --shared-v8-includes=$V8_ROOT/include \
    # --shared-v8-libpath=$V8_ROOT/out/nacl_ia32.release/lib.target
    # --shared-libuv \
    # --shared-http-parser \
    # --shared-cares \
    # --shared-zlib